export {default as User} from './user'
export {default as Course} from './course'
export {default as Contact} from './contact'
export {default as About} from './about'
export {default as Image} from './image'